version: '3'
services:
  httpd:
    build:
      context: ./httpd
      dockerfile: Dockerfile
    expose:
      - 80
      - 443
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src/main/webapp:/usr/local/apache2/htdocs
      - ./target/webjars/META-INF/resources/webjars:/usr/local/apache2/htdocs/webjars
      - ./src/main/resources:/usr/local/apache2/htdocs/settings
