version: '3'
services:
  httpd:
    build:
      context: ./httpd
      dockerfile: Dockerfile
    expose:
      - 80
      - 443
    ports:
      - 80:80
      - 443:443
    volumes:
      - settings:/usr/local/apache2/htdocs/settings
volumes:
  settings:
    external: true
